name: units_converter
description: Simple and light units conversion package for all your needs.
version: 1.2.0
homepage: https://github.com/ferraridamiano/units_converter

environment:
  sdk: '>=2.17.0 <3.0.0'

dev_dependencies:
  lints: ^1.0.1
  test: ^1.21.1
